#!/bin/bash

# Script para configurar variables de entorno en Vercel

echo "🔧 Configuración de Variables de Entorno en Vercel"
echo ""
echo "Para que el frontend en producción use el API correcto:"
echo ""
echo "1️⃣  Ve a tu proyecto en Vercel:"
echo "   https://vercel.com/tu-usuario/random"
echo ""
echo "2️⃣  Settings → Environment Variables"
echo ""
echo "3️⃣  Agrega esta variable:"
echo ""
echo "   Key:   VITE_ANALYTICS_API"
echo "   Value: http://api.random-studio.io/analytics"
echo "   Environments: [x] Production  [x] Preview  [ ] Development"
echo ""
echo "4️⃣  Click 'Save'"
echo ""
echo "5️⃣  Redeploy tu aplicación:"
echo "   Deployments → ... → Redeploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "O más fácil, haz push y Vercel usará .env.production automáticamente:"
echo ""
echo "   git add .env.production"
echo "   git commit -m 'fix: configurar analytics API para producción'"
echo "   git push origin main"
echo ""
echo "✅ Vercel detectará .env.production y lo usará en producción"
echo ""
