"""Puertos que implementa infrastructure."""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass
from datetime import datetime
from typing import Protocol

from futbol.domain.balancer import ConstraintKind, Evaluation, Partition
from futbol.domain.models import Match, Player, Role, Signup, SkillInfo
from futbol.domain.results import MatchResult, PlayedMatch
from futbol.domain.schedule import MatchWindow, ScheduleConfig
from futbol.domain.skills import SkillRating


@dataclass(frozen=True)
class Actor:
    user_id: str
    group_id: str
    role: Role
    email: str
    player_id: str | None
    has_password: bool = False

    @property
    def is_admin(self) -> bool:
        return self.role == "admin"


class Mailer(Protocol):
    async def send_magic_link(self, email: str, link: str) -> None: ...


class FutbolRepository(Protocol):
    # auth
    async def email_known(self, email: str) -> bool: ...
    async def save_magic_link(self, token_hash: str, email: str, expires_at: datetime) -> None: ...
    async def consume_magic_link(self, token_hash: str, now: datetime) -> str | None: ...
    async def get_or_create_user(self, email: str) -> str: ...
    async def default_group_id(self) -> str: ...
    async def ensure_membership(self, group_id: str, user_id: str, role: Role, promote: bool) -> None: ...
    async def link_player_by_email(self, group_id: str, user_id: str, email: str) -> None: ...
    async def save_session(self, token_hash: str, user_id: str, expires_at: datetime) -> None: ...
    async def actor_for_session(self, token_hash: str, now: datetime) -> Actor | None: ...
    async def actor_for_user(self, user_id: str) -> Actor | None: ...
    async def delete_session(self, token_hash: str) -> None: ...
    async def password_hash_for(self, email: str) -> tuple[str, str | None] | None: ...
    async def set_password_hash(self, user_id: str, password_hash: str, now: datetime) -> None: ...

    # skills
    async def list_skills(self, group_id: str) -> list[SkillInfo]: ...
    async def create_skill(self, group_id: str, skill: SkillInfo) -> SkillInfo: ...
    async def update_skill(self, group_id: str, skill: SkillInfo) -> SkillInfo | None: ...

    # players
    async def list_players(self, group_id: str) -> list[Player]: ...
    async def get_player(self, group_id: str, player_id: str) -> Player | None: ...
    async def create_player(self, group_id: str, player: Player) -> Player: ...
    async def update_player(self, group_id: str, player: Player) -> Player | None: ...

    # ratings
    async def list_group_ratings(self, group_id: str) -> list[SkillRating]: ...
    async def list_ratings_by(self, rater_player_id: str, player_id: str) -> dict[str, int]: ...
    async def upsert_ratings(self, rater_player_id: str, player_id: str, values: dict[str, int]) -> None: ...


SignupMutation = Callable[[Match, list[Signup]], list[Signup]]


class MatchRepository(Protocol):
    async def list_group_ids(self) -> list[str]: ...
    async def get_schedule(self, group_id: str) -> ScheduleConfig: ...
    async def recent_matches(self, group_id: str, since: datetime) -> list[Match]: ...
    async def create_match(self, group_id: str, window: MatchWindow) -> None: ...
    async def close_matches(self, match_ids: tuple[str, ...]) -> None: ...
    async def current_match(self, group_id: str) -> Match | None: ...
    async def get_match(self, group_id: str, match_id: str) -> Match | None: ...
    async def list_signups(self, match_id: str) -> list[Signup]: ...
    async def mutate_signups(self, match_id: str, mutation: SignupMutation) -> list[Signup]:
        """Aplica `mutation` con el partido bloqueado (FOR UPDATE): dos inscripciones simultáneas
        no pueden ocupar el mismo último lugar."""
        ...


@dataclass(frozen=True)
class StoredConstraint:
    id: str
    player_a: str
    player_b: str
    kind: ConstraintKind


class TeamsRepository(Protocol):
    async def balancer_overrides(self, group_id: str) -> dict[str, object] | None: ...
    async def save_proposals(self, match_id: str, proposals: list[Evaluation]) -> None:
        """Reemplaza las propuestas del partido (rank = posición + 1)."""
        ...

    async def list_proposals(self, match_id: str) -> list[Evaluation]: ...
    async def delete_proposals(self, match_id: str) -> None: ...
    async def publish(self, match_id: str, partition: Partition) -> None:
        """Copia los equipos a match_teams y pasa el partido a teams_published (una transacción)."""
        ...

    async def published(self, match_id: str) -> Partition | None: ...
    async def recent_partitions(self, group_id: str, before_match_id: str, limit: int) -> list[Partition]: ...
    async def pending_matches(self, group_id: str) -> list[str]:
        """Partidos cerrados, sin propuestas ni equipos publicados (para el cron)."""
        ...

    async def list_constraints(self, group_id: str) -> list[StoredConstraint]: ...
    async def add_constraint(self, group_id: str, a: str, b: str, kind: ConstraintKind) -> StoredConstraint: ...
    async def delete_constraint(self, group_id: str, constraint_id: str) -> bool: ...


class ResultsRepository(Protocol):
    async def get_result(self, match_id: str) -> MatchResult | None: ...
    async def save_result(
        self,
        match_id: str,
        result: MatchResult,
        lineup: Partition,
        recorded_by: str,
        player_goals: Mapping[str, int],
    ) -> None:
        """En una transacción: reemplaza match_teams por quién jugó (con sus goles), guarda el resultado y pasa a
        `played`."""
        ...

    async def player_goals(self, match_id: str) -> dict[str, int]: ...
    async def goal_rates(self, group_id: str, window: int) -> dict[str, float]:
        """Promedio de goles por partido de cada jugador en sus últimos `window` partidos con dato."""
        ...

    async def history(self, group_id: str, limit: int) -> list[PlayedMatch]:
        """Partidos jugados, del más reciente al más viejo."""
        ...
